package storage_test

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// smartQuotes are the curly quote runes, written as escapes so this file stays
// ASCII and does not trip its own check.
const smartQuotes = "\u2018\u2019\u201c\u201d"

// TestNoSmartQuotesInGoSource guards against curly quotes reaching Go source.
//
// They are rarely typed by hand. gofmt puts them there: its doc comment
// formatter applies the old godoc typographic convention, rewriting a pair of
// backticks and a pair of apostrophes into curly quotes. So an empty SQL string
// literal written correctly as two apostrophes in doc comment prose is silently
// reformatted into one curly quote, which is not valid SQL, and the damage shows up in a
// later commit rather than the one that wrote it.
//
// Indented code blocks and comments inside function bodies are left alone, so
// that is where a snippet containing quotes belongs.
func TestNoSmartQuotesInGoSource(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			// docs/ is generated by swag; .worktrees holds sibling checkouts.
			switch d.Name() {
			case ".git", "docs", "node_modules", ".worktrees":
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for i, line := range strings.Split(string(content), "\n") {
			if strings.ContainsAny(line, smartQuotes) {
				rel, _ := filepath.Rel(root, path)
				t.Errorf("%s:%d contains a smart quote; use a plain apostrophe or double quote: %s",
					rel, i+1, strings.TrimSpace(line))
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}
